import type { SectionLayout, SectionType } from '../../../shared/types';

/** Professional preset — best practices for formal CVs and ATS compatibility. */
export const professionalLayouts: Record<SectionType, SectionLayout> = {
  summary: {
    presetId: 'professional',
    dateSlot: 'hidden',
    iconStyle: 'none',
    separator: 'none',
    density: 'compact',
    columns: 1,
  },
  education: {
    presetId: 'professional',
    dateSlot: 'right-inline',
    iconStyle: 'none',
    separator: 'none',
    density: 'compact',
    columns: 1,
  },
  skills: {
    presetId: 'professional',
    dateSlot: 'hidden',
    iconStyle: 'none',
    separator: 'none',
    density: 'compact',
    columns: 2,
  },
  certifications: {
    presetId: 'professional',
    dateSlot: 'right-inline',
    iconStyle: 'none',
    separator: 'none',
    density: 'compact',
    columns: 1,
  },
  projects: {
    presetId: 'professional',
    dateSlot: 'hidden',
    iconStyle: 'bullet',
    separator: 'none',
    density: 'compact',
    columns: 1,
  },
  awards: {
    presetId: 'professional',
    dateSlot: 'right-inline',
    iconStyle: 'none',
    separator: 'none',
    density: 'compact',
    columns: 1,
  },
  volunteering: {
    presetId: 'professional',
    dateSlot: 'right-inline',
    iconStyle: 'none',
    separator: 'none',
    density: 'compact',
    columns: 1,
  },
  'work-experience': {
    presetId: 'professional',
    dateSlot: 'right-inline',
    iconStyle: 'bullet',
    separator: 'none',
    density: 'compact',
    columns: 1,
  },
  custom: {
    presetId: 'professional',
    dateSlot: 'right-inline',
    iconStyle: 'bullet',
    separator: 'none',
    density: 'compact',
    columns: 1,
  },
};
